"use client";
import type { ProjectServiceRecord, ProjectServiceStatus } from '@zyllen/shared';
import { Button } from '@web/components/ui/button';
import { PROJECT_SERVICE_COPY as copy } from '@web/lib/brand-voice';

interface Props { records: ProjectServiceRecord[]; canEdit: boolean; pending: boolean; onEdit: (record: ProjectServiceRecord) => void; onStatus: (record: ProjectServiceRecord, status: ProjectServiceStatus) => void }
export function ProjectServiceTable({ records, canEdit, pending, onEdit, onStatus }: Props) {
    return <div className="overflow-x-auto border-y border-white/10"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[0.02] text-[10px] uppercase tracking-[0.12em] text-white/40"><tr>{[copy.name, copy.type, copy.status, copy.planned, copy.responsibles, copy.actions].map(label => <th key={label} scope="col" className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{records.map(record => <tr key={record.id} data-project-service-id={record.id} className="align-top transition-colors hover:bg-white/[0.025]">
        <td className="max-w-xs border-l-4 px-4 py-4" style={{ borderLeftColor: record.color }}>{record.marker && <p data-service-marker className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-[var(--zyllen-highlight)]">{record.marker.name}</p>}<p className="break-words font-medium text-white">{record.name}</p><p className="mt-1 text-xs text-[var(--zyllen-muted)]">{record.company.name}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px]"><span className={record.urgency === 2 ? 'text-red-300' : 'text-[var(--zyllen-muted)]'}>{copy.urgencies[record.urgency]}</span>{record.requiresTravel && <span className="text-blue-300">{copy.travel}</span>}{record.relevant && <span className="text-[var(--zyllen-highlight)]">{copy.relevant}</span>}</div>{record.mapsUrl && <a href={record.mapsUrl} target="_blank" rel="noopener noreferrer" className="mt-2 block text-xs text-[var(--zyllen-highlight)] hover:underline">{copy.openMaps}</a>}</td>
        <td className="px-4 py-4 text-[var(--zyllen-muted)]">{copy.types[record.type]}</td><td className="px-4 py-4"><span className="text-xs text-white">{copy.statuses[record.status]}</span>{record.completedAt && <p className="mt-1 text-[10px] text-[var(--zyllen-muted)]">{copy.completed}: {new Date(record.completedAt).toLocaleString('pt-BR')}</p>}</td>
        <td className="whitespace-nowrap px-4 py-4 text-xs text-[var(--zyllen-muted)]">{record.schedule ? <>{new Date(record.schedule.startDate).toLocaleString('pt-BR')}<br />{new Date(record.schedule.endDate).toLocaleString('pt-BR')}</> : copy.noDate}</td>
        <td className="max-w-xs px-4 py-4 text-xs text-[var(--zyllen-muted)]">{record.internalAssignees.map(user => <p key={user.id}>{user.name}</p>)}{record.contractors.map(user => <p key={user.id}>{user.name} · {copy.contractor}</p>)}{!record.internalAssignees.length && !record.contractors.length && copy.notAssigned}{record.sectors.length > 0 && <p className="mt-2">{record.sectors.join(', ')}</p>}</td>
        <td className="px-4 py-4"><div className="flex flex-col items-start gap-2"><Button type="button" size="sm" variant="outline" disabled={pending} onClick={() => onEdit(record)}>{canEdit ? copy.edit : copy.details}</Button>{canEdit ? <select aria-label={`${copy.status}: ${record.name}`} className="max-w-44 rounded-md border border-[var(--zyllen-border)] bg-[var(--zyllen-bg)] px-2 py-1.5 text-xs text-white" value={record.status} disabled={pending} onChange={event => onStatus(record, event.target.value as ProjectServiceStatus)}>{(record.schedule ? ['SCHEDULED', 'IN_PROGRESS', 'DONE', 'CANCELLED'] : ['PENDING', 'CANCELLED']).map(status => <option key={status} value={status}>{copy.statuses[status as ProjectServiceStatus]}</option>)}</select> : <span className="text-xs text-[var(--zyllen-muted)]">{copy.readOnly}</span>}</div></td>
    </tr>)}</tbody></table></div>;
}
