"use client";
import type { OperationsStatistics, OperationServiceHighlight } from '@zyllen/shared';
import { Button } from '@web/components/ui/button';
import { Skeleton } from '@web/components/ui/skeleton';
import { EmptyState, ListSectionHeader } from '@web/components/ui/workspace';
import { OPERATIONS_DASHBOARD_COPY as copy, PROJECT_SERVICE_COPY as serviceCopy, TRIP_COPY as tripCopy } from '@web/lib/brand-voice';

function ServiceSection({ title, context, items, history = false }: { title: string; context: string; items: OperationServiceHighlight[]; history?: boolean }) {
    return <section aria-label={title} className="min-w-0 space-y-3"><ListSectionHeader title={title} count={items.length} description={context} />{items.length ? <ul className="divide-y divide-white/10 border-y border-white/10">{items.map(service => <li key={service.id} data-operation-service={service.id} className="min-w-0 px-4 py-4 transition-colors hover:bg-white/[0.025]" style={{ boxShadow: `inset 2px 0 0 ${/^#[a-fA-F0-9]{6}$/.test(service.color) ? service.color : '#ABFF10'}` }}>
        {service.markerName && <p className="mb-1 text-xs font-medium text-[var(--zyllen-highlight)] [overflow-wrap:anywhere]">{service.markerName}</p>}<h3 className="font-semibold text-white [overflow-wrap:anywhere]">{service.name}</h3><p className="mt-1 text-xs text-[var(--zyllen-muted)] [overflow-wrap:anywhere]">{service.companyName} · {serviceCopy.types[service.type]}</p>
        <div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className="rounded-md bg-white/5 px-2 py-1 text-white">{serviceCopy.statuses[service.status] ?? service.status}</span>{!history && <span className={`rounded-md px-2 py-1 ${service.urgency === 2 ? 'bg-red-500/15 text-red-200' : 'bg-white/5 text-[var(--zyllen-muted)]'}`}>{serviceCopy.urgencies[service.urgency]}</span>}</div>
        <p className="mt-3 text-xs text-[var(--zyllen-muted)]">{history && service.completedAt ? `${copy.completed}: ${new Date(service.completedAt).toLocaleString('pt-BR')}` : service.startDate ? `${copy.planned}: ${new Date(service.startDate).toLocaleString('pt-BR')}` : copy.noDate}</p>
    </li>)}</ul> : <EmptyState title={copy.empty} className="min-h-32" />}</section>;
}
interface Props { data?: OperationsStatistics; loading: boolean; failed: boolean; fetching: boolean; onRetry: () => void }

export function OperationsDashboardView({ data, loading, failed, fetching, onRetry }: Props) {
    const metrics = data ? [{ key: 'installations', label: copy.installations, value: data.installationsCompleted, context: copy.actualContext }, { key: 'removals', label: copy.removals, value: data.removalsCompleted, context: copy.actualContext },
        { key: 'planned-trips', label: copy.plannedTrips, value: data.tripsPlanned, context: copy.plannedContext }, { key: 'completed-trips', label: copy.completedTrips, value: data.tripsCompleted, context: copy.actualContext }] : [];
    return <div className="space-y-5">{failed && <div role="alert" className="rounded-xl border border-red-400/50 bg-red-500/10 p-4 text-sm text-red-200"><p>{copy.loadError}</p>{data && <p className="mt-1">{copy.stale}</p>}<Button type="button" variant="ghost" size="sm" className="mt-2" disabled={fetching} onClick={onRetry}>{copy.retry}</Button></div>}
        {loading ? <div className="grid border-y border-white/10 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="border-b border-white/10 p-4 sm:border-b-0 sm:border-r"><Skeleton className="h-3 w-24" /><Skeleton className="mt-3 h-8 w-12" /><Skeleton className="mt-2 h-3 w-20" /></div>)}</div> : data && <>
            <div className="grid divide-y divide-white/10 border-y border-white/10 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{metrics.map(metric => <div key={metric.key} data-operation-metric={metric.key} className="min-w-0 px-4 py-5"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-white/40">{metric.label}</p><p data-metric-value className="mt-2 font-mono text-3xl font-semibold tabular-nums text-white">{metric.value}</p><p className="mt-1 text-[10px] text-[var(--zyllen-muted)]">{metric.context}</p></div>)}</div>
            <p className="flex flex-wrap gap-x-6 gap-y-2 border-y border-white/10 px-4 py-3 text-xs text-[var(--zyllen-muted)]"><span>{copy.currentPlanned}: <strong className="font-mono tabular-nums text-white">{data.current.plannedTrips}</strong></span><span>{copy.inProgress}: <strong className="font-mono tabular-nums text-white">{data.current.tripsInProgress}</strong></span></p>
            {(data.dataQuality.servicesCompletedWithoutDate > 0 || data.dataQuality.tripsCompletedWithoutDate > 0 || data.dataQuality.travelWithoutBooking > 0 || data.dataQuality.unclassified > 0) && <div role="status" className="space-y-2 border-l-2 border-amber-400 bg-amber-400/5 px-4 py-3 text-sm text-amber-200">{(data.dataQuality.servicesCompletedWithoutDate > 0 || data.dataQuality.tripsCompletedWithoutDate > 0) && <p>{copy.missingDates(data.dataQuality.servicesCompletedWithoutDate, data.dataQuality.tripsCompletedWithoutDate)}</p>}{data.dataQuality.travelWithoutBooking > 0 && <p>{copy.withoutBooking(data.dataQuality.travelWithoutBooking)}</p>}{data.dataQuality.unclassified > 0 && <p>{copy.unclassified(data.dataQuality.unclassified)}</p>}</div>}
            <div className="grid gap-6 xl:grid-cols-2"><ServiceSection title={copy.nextInstallations} context={copy.upcomingContext} items={data.nextInstallations} /><ServiceSection title={copy.relevantInstallations} context={copy.relevantContext} items={data.relevantInstallations} /><ServiceSection title={copy.latestInstallations} context={copy.latestContext} items={data.latestInstallations} history /><ServiceSection title={copy.latestRemovals} context={copy.latestContext} items={data.latestRemovals} history />
                <section aria-label={copy.nextTrips} className="min-w-0 space-y-3"><ListSectionHeader title={copy.nextTrips} count={data.nextInterstateTrips.length} description={copy.upcomingContext} />{data.nextInterstateTrips.length ? <ul className="divide-y divide-white/10 border-y border-white/10">{data.nextInterstateTrips.map(trip => <li key={trip.id} data-operation-trip={trip.id} className="min-w-0 px-4 py-4 transition-colors hover:bg-white/[0.025]"><h3 className="font-semibold text-white [overflow-wrap:anywhere]">{trip.title}</h3><p className="mt-1 text-xs text-[var(--zyllen-muted)] [overflow-wrap:anywhere]">{trip.originCity}/{trip.originState} → {trip.destinationCity}/{trip.destinationState}</p><p className="mt-3 text-xs text-[var(--zyllen-muted)]">{tripCopy.departure}: {new Date(trip.startDate).toLocaleString('pt-BR')}<br />{tripCopy.return}: {new Date(trip.endDate).toLocaleString('pt-BR')}</p><p className="mt-2 text-xs text-[var(--zyllen-muted)]">{tripCopy.count(trip.serviceCount)}</p></li>)}</ul> : <EmptyState title={copy.empty} className="min-h-32" />}</section>
            </div><p className="text-xs text-[var(--zyllen-muted)]">{copy.updated(new Date(data.generatedAt).toLocaleString('pt-BR'))}</p>
        </>}
    </div>;
}
